version: '3'

services:
  db:
    # build: .でdocker-compose.ymlと同じフォルダにDockerfileがあることを示す
    build: .
    container_name: postgres_pta
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'evidea'
volumes:
  db-store:
    driver: local